[build]
builder = "DOCKERFILE"
dockerfilePath = "globetrotter-api/Dockerfile"

[deploy]
startCommand = "dotnet globetrotter-api.dll"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"